remove ngix

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -1,12 +1,33 @@
-FROM node:20-alpine AS build
+# FROM node:20-alpine AS build
+# WORKDIR /app
+# COPY package*.json ./
+# RUN npm install
+# COPY . .
+# RUN npm run build
+
+# # FROM nginx:1.27-alpine
+# # COPY nginx.conf /etc/nginx/conf.d/default.conf
+# # COPY --from=build /app/dist /usr/share/nginx/html
+# EXPOSE 80
+# HEALTHCHECK --interval=15s --timeout=3s --retries=5 CMD wget -qO- http://localhost/ >/dev/null || exit 1
+
+
+FROM node:20-alpine
+
 WORKDIR /app
+
 COPY package*.json ./
 RUN npm install
+
 COPY . .
+
 RUN npm run build
 
-FROM nginx:1.27-alpine
-COPY nginx.conf /etc/nginx/conf.d/default.conf
-COPY --from=build /app/dist /usr/share/nginx/html
-EXPOSE 80
-HEALTHCHECK --interval=15s --timeout=3s --retries=5 CMD wget -qO- http://localhost/ >/dev/null || exit 1
+RUN npm install -g serve
+
+EXPOSE 10000
+
+HEALTHCHECK --interval=15s --timeout=3s --retries=5 \
+  CMD wget -qO- http://localhost:10000/ >/dev/null || exit 1
+
+CMD ["serve", "-s", "dist", "-l", "10000"]
